# Generated by Django 3.1.5 on 2021-01-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_list',
            name='item_price',
            field=models.CharField(default=32, max_length=10),
            preserve_default=False,
        ),
    ]
